// Expanded universe of real listed companies across global exchanges.
// Used as Mock data inside Markets > Global Markets. Live quotes remain only
// for the small curated list inside `stocks-data.ts`; everything here is
// rendered with a deterministic synthetic quote for performance & no API costs.

import type { CompanyDef, StockRegion } from "./stocks-data";

type Mini = [symbol: string, name: string, sector: string];

function expand(arr: Mini[], currency: string, baseRef: number): CompanyDef[] {
  return arr.map(([symbol, name, sector]) => {
    const seed = (symbol.charCodeAt(0) + symbol.charCodeAt(symbol.length - 1) + symbol.length) % 100;
    const baseline = baseRef * (0.35 + (seed / 100) * 1.8);
    return { symbol, name, sector, baseline, currency };
  });
}

// =============== US (NYSE + NASDAQ) ===============
const US: Mini[] = [
  ["AAPL","Apple","Technology"],["MSFT","Microsoft","Technology"],["NVDA","NVIDIA","Semiconductors"],
  ["GOOGL","Alphabet Class A","Technology"],["GOOG","Alphabet Class C","Technology"],["AMZN","Amazon","E-commerce"],
  ["META","Meta Platforms","Social Media"],["TSLA","Tesla","Automotive"],["BRK.B","Berkshire Hathaway","Conglomerate"],
  ["JPM","JPMorgan Chase","Banking"],["V","Visa","Payments"],["MA","Mastercard","Payments"],
  ["UNH","UnitedHealth","Healthcare"],["XOM","ExxonMobil","Energy"],["JNJ","Johnson & Johnson","Pharma"],
  ["PG","Procter & Gamble","Consumer"],["HD","Home Depot","Retail"],["AVGO","Broadcom","Semiconductors"],
  ["CVX","Chevron","Energy"],["LLY","Eli Lilly","Pharma"],["ABBV","AbbVie","Pharma"],["KO","Coca-Cola","Beverages"],
  ["PEP","PepsiCo","Beverages"],["MRK","Merck","Pharma"],["COST","Costco","Retail"],["WMT","Walmart","Retail"],
  ["BAC","Bank of America","Banking"],["MCD","McDonald's","Restaurants"],["TMO","Thermo Fisher","Life Sciences"],
  ["CSCO","Cisco","Networking"],["ACN","Accenture","IT Services"],["ABT","Abbott","Healthcare"],
  ["NKE","Nike","Apparel"],["ADBE","Adobe","Software"],["NFLX","Netflix","Streaming"],["CRM","Salesforce","Software"],
  ["DIS","Walt Disney","Media"],["AMD","AMD","Semiconductors"],["INTC","Intel","Semiconductors"],
  ["QCOM","Qualcomm","Semiconductors"],["TXN","Texas Instruments","Semiconductors"],["IBM","IBM","Technology"],
  ["ORCL","Oracle","Software"],["NOW","ServiceNow","Software"],["INTU","Intuit","Software"],
  ["AMAT","Applied Materials","Semiconductors"],["MU","Micron","Semiconductors"],["PYPL","PayPal","Payments"],
  ["UBER","Uber","Mobility"],["LYFT","Lyft","Mobility"],["SHOP","Shopify","E-commerce"],["SQ","Block","Payments"],
  ["SPOT","Spotify","Streaming"],["ABNB","Airbnb","Travel"],["BKNG","Booking","Travel"],["MAR","Marriott","Hospitality"],
  ["CMCSA","Comcast","Telecom"],["VZ","Verizon","Telecom"],["T","AT&T","Telecom"],["TMUS","T-Mobile","Telecom"],
  ["BA","Boeing","Aerospace"],["LMT","Lockheed Martin","Defense"],["RTX","RTX","Defense"],["GE","GE Aerospace","Industrial"],
  ["CAT","Caterpillar","Industrial"],["DE","Deere","Industrial"],["HON","Honeywell","Industrial"],
  ["UNP","Union Pacific","Rail"],["UPS","UPS","Logistics"],["FDX","FedEx","Logistics"],["DAL","Delta Air Lines","Airlines"],
  ["UAL","United Airlines","Airlines"],["AAL","American Airlines","Airlines"],["LUV","Southwest","Airlines"],
  ["F","Ford","Automotive"],["GM","General Motors","Automotive"],["RIVN","Rivian","Automotive"],["LCID","Lucid","Automotive"],
  ["GS","Goldman Sachs","Banking"],["MS","Morgan Stanley","Banking"],["WFC","Wells Fargo","Banking"],["C","Citigroup","Banking"],
  ["BLK","BlackRock","Asset Management"],["SCHW","Charles Schwab","Brokerage"],["AXP","American Express","Payments"],
  ["AIG","AIG","Insurance"],["MET","MetLife","Insurance"],["PRU","Prudential","Insurance"],["TRV","Travelers","Insurance"],
  ["COP","ConocoPhillips","Energy"],["EOG","EOG Resources","Energy"],["SLB","Schlumberger","Energy"],
  ["OXY","Occidental","Energy"],["PSX","Phillips 66","Energy"],["MPC","Marathon Petroleum","Energy"],
  ["VLO","Valero","Energy"],["KMI","Kinder Morgan","Energy"],["WMB","Williams","Energy"],
  ["NEE","NextEra Energy","Utilities"],["DUK","Duke Energy","Utilities"],["SO","Southern Co","Utilities"],
  ["AEP","American Electric","Utilities"],["EXC","Exelon","Utilities"],["D","Dominion Energy","Utilities"],
  ["PFE","Pfizer","Pharma"],["BMY","Bristol-Myers","Pharma"],["GILD","Gilead","Pharma"],["AMGN","Amgen","Pharma"],
  ["REGN","Regeneron","Pharma"],["VRTX","Vertex","Pharma"],["BIIB","Biogen","Pharma"],["MRNA","Moderna","Pharma"],
  ["CVS","CVS Health","Pharmacy"],["WBA","Walgreens","Pharmacy"],["ELV","Elevance Health","Healthcare"],
  ["HUM","Humana","Healthcare"],["CI","Cigna","Healthcare"],["ISRG","Intuitive Surgical","Medical Devices"],
  ["MDT","Medtronic","Medical Devices"],["SYK","Stryker","Medical Devices"],["BSX","Boston Scientific","Medical Devices"],
  ["DHR","Danaher","Life Sciences"],["LIN","Linde","Chemicals"],["APD","Air Products","Chemicals"],["SHW","Sherwin-Williams","Chemicals"],
  ["ECL","Ecolab","Chemicals"],["DD","DuPont","Chemicals"],["DOW","Dow","Chemicals"],["FCX","Freeport-McMoRan","Mining"],
  ["NEM","Newmont","Mining"],["NUE","Nucor","Steel"],["X","US Steel","Steel"],
  ["TGT","Target","Retail"],["LOW","Lowe's","Retail"],["TJX","TJX","Retail"],["DG","Dollar General","Retail"],
  ["DLTR","Dollar Tree","Retail"],["KR","Kroger","Retail"],["SBUX","Starbucks","Restaurants"],["CMG","Chipotle","Restaurants"],
  ["YUM","Yum! Brands","Restaurants"],["MDLZ","Mondelez","Food"],["KHC","Kraft Heinz","Food"],["GIS","General Mills","Food"],
  ["CL","Colgate-Palmolive","Consumer"],["KMB","Kimberly-Clark","Consumer"],["MO","Altria","Tobacco"],["PM","Philip Morris","Tobacco"],
  ["EL","Estée Lauder","Cosmetics"],["LULU","Lululemon","Apparel"],["DECK","Deckers","Apparel"],["RL","Ralph Lauren","Apparel"],
  ["TPR","Tapestry","Luxury"],["NWL","Newell Brands","Consumer"],
  ["PLD","Prologis","REIT"],["AMT","American Tower","REIT"],["CCI","Crown Castle","REIT"],["EQIX","Equinix","REIT"],
  ["SPG","Simon Property","REIT"],["O","Realty Income","REIT"],["PSA","Public Storage","REIT"],
  ["PANW","Palo Alto Networks","Cybersecurity"],["CRWD","CrowdStrike","Cybersecurity"],["ZS","Zscaler","Cybersecurity"],
  ["FTNT","Fortinet","Cybersecurity"],["OKTA","Okta","Cybersecurity"],["DDOG","Datadog","Software"],
  ["SNOW","Snowflake","Software"],["MDB","MongoDB","Software"],["NET","Cloudflare","Software"],["TEAM","Atlassian","Software"],
  ["WDAY","Workday","Software"],["DOCU","DocuSign","Software"],["TWLO","Twilio","Software"],["ZM","Zoom","Software"],
  ["ROKU","Roku","Streaming"],["PINS","Pinterest","Social Media"],["SNAP","Snap","Social Media"],
  ["DASH","DoorDash","Food Delivery"],["COIN","Coinbase","Crypto"],["HOOD","Robinhood","Brokerage"],
  ["PLTR","Palantir","Software"],["NIO","NIO","Automotive"],["BIDU","Baidu","Technology"],
  ["BABA","Alibaba","E-commerce"],["JD","JD.com","E-commerce"],["PDD","PDD Holdings","E-commerce"],
  ["TSM","TSMC","Semiconductors"],["ASML","ASML","Semiconductors"],["SAP","SAP","Software"],
  ["NVO","Novo Nordisk","Pharma"],["TM","Toyota ADR","Automotive"],["HSBC","HSBC","Banking"],
  ["BP","BP","Energy"],["RIO","Rio Tinto","Mining"],["BHP","BHP","Mining"],["SHEL","Shell","Energy"],
];

// =============== EU (Euronext + XETRA) ===============
const EU: Mini[] = [
  ["MC.PA","LVMH","Luxury"],["ASML.AS","ASML","Semiconductors"],["SAP.DE","SAP","Software"],
  ["SIE.DE","Siemens","Industrial"],["TTE.PA","TotalEnergies","Energy"],["AIR.PA","Airbus","Aerospace"],
  ["OR.PA","L'Oréal","Cosmetics"],["RMS.PA","Hermès","Luxury"],["SAN.PA","Sanofi","Pharma"],["BNP.PA","BNP Paribas","Banking"],
  ["GLE.PA","Société Générale","Banking"],["ACA.PA","Crédit Agricole","Banking"],["CS.PA","AXA","Insurance"],
  ["AI.PA","Air Liquide","Chemicals"],["SU.PA","Schneider Electric","Industrial"],["VIE.PA","Veolia","Utilities"],
  ["EN.PA","Bouygues","Construction"],["DG.PA","Vinci","Construction"],["SGO.PA","Saint-Gobain","Materials"],
  ["KER.PA","Kering","Luxury"],["DSY.PA","Dassault Systèmes","Software"],["CAP.PA","Capgemini","IT Services"],
  ["ORA.PA","Orange","Telecom"],["RNO.PA","Renault","Automotive"],["UG.PA","Peugeot","Automotive"],
  ["STLAM.MI","Stellantis","Automotive"],["ENEL.MI","Enel","Utilities"],["ENI.MI","Eni","Energy"],
  ["ISP.MI","Intesa Sanpaolo","Banking"],["UCG.MI","UniCredit","Banking"],["RACE.MI","Ferrari","Automotive"],
  ["G.MI","Generali","Insurance"],["TIT.MI","Telecom Italia","Telecom"],["MB.MI","Mediobanca","Banking"],
  ["VOW3.DE","Volkswagen","Automotive"],["BMW.DE","BMW","Automotive"],["MBG.DE","Mercedes-Benz","Automotive"],
  ["DAI.DE","Daimler Truck","Automotive"],["ALV.DE","Allianz","Insurance"],["DBK.DE","Deutsche Bank","Banking"],
  ["BAS.DE","BASF","Chemicals"],["BAYN.DE","Bayer","Pharma"],["DTE.DE","Deutsche Telekom","Telecom"],
  ["DPW.DE","DHL Group","Logistics"],["IFX.DE","Infineon","Semiconductors"],["MUV2.DE","Munich Re","Insurance"],
  ["RWE.DE","RWE","Utilities"],["EOAN.DE","E.ON","Utilities"],["FRE.DE","Fresenius","Healthcare"],
  ["HEN3.DE","Henkel","Consumer"],["ADS.DE","Adidas","Apparel"],["PUM.DE","Puma","Apparel"],
  ["ZAL.DE","Zalando","E-commerce"],["DHER.DE","Delivery Hero","Food Delivery"],["HEI.DE","Heidelberg Materials","Materials"],
  ["MRK.DE","Merck KGaA","Pharma"],["LIN.DE","Linde","Chemicals"],["INGA.AS","ING","Banking"],
  ["AD.AS","Ahold Delhaize","Retail"],["PHIA.AS","Philips","Healthcare"],["UNA.AS","Unilever NV","Consumer"],
  ["HEIA.AS","Heineken","Beverages"],["RAND.AS","Randstad","HR"],["DSM.AS","DSM-Firmenich","Chemicals"],
  ["WKL.AS","Wolters Kluwer","Information"],["ABI.BR","AB InBev","Beverages"],["UCB.BR","UCB","Pharma"],
  ["KBC.BR","KBC","Banking"],["NOVN.SW","Novartis","Pharma"],["ROG.SW","Roche","Pharma"],
  ["NESN.SW","Nestlé","Food"],["UHR.SW","Swatch","Luxury"],["CFR.SW","Richemont","Luxury"],
  ["ITX.MC","Inditex","Retail"],["SAN.MC","Banco Santander","Banking"],["BBVA.MC","BBVA","Banking"],
  ["TEF.MC","Telefónica","Telecom"],["IBE.MC","Iberdrola","Utilities"],["REP.MC","Repsol","Energy"],
];

// =============== UK (LSE) ===============
const UK: Mini[] = [
  ["SHEL.L","Shell","Energy"],["AZN.L","AstraZeneca","Pharma"],["HSBA.L","HSBC","Banking"],["BP.L","BP","Energy"],
  ["ULVR.L","Unilever","Consumer"],["GSK.L","GSK","Pharma"],["RIO.L","Rio Tinto","Mining"],["GLEN.L","Glencore","Mining"],
  ["AAL.L","Anglo American","Mining"],["BARC.L","Barclays","Banking"],["LLOY.L","Lloyds","Banking"],["NWG.L","NatWest","Banking"],
  ["STAN.L","Standard Chartered","Banking"],["PRU.L","Prudential","Insurance"],["LGEN.L","Legal & General","Insurance"],
  ["AV.L","Aviva","Insurance"],["BATS.L","BAT","Tobacco"],["IMB.L","Imperial Brands","Tobacco"],["DGE.L","Diageo","Beverages"],
  ["RKT.L","Reckitt","Consumer"],["TSCO.L","Tesco","Retail"],["SBRY.L","Sainsbury's","Retail"],["MKS.L","M&S","Retail"],
  ["NXT.L","Next","Retail"],["BME.L","B&M","Retail"],["KGF.L","Kingfisher","Retail"],["BT-A.L","BT Group","Telecom"],
  ["VOD.L","Vodafone","Telecom"],["NG.L","National Grid","Utilities"],["SSE.L","SSE","Utilities"],["CNA.L","Centrica","Utilities"],
  ["UU.L","United Utilities","Utilities"],["SVT.L","Severn Trent","Utilities"],["IAG.L","IAG","Airlines"],["EZJ.L","easyJet","Airlines"],
  ["RR.L","Rolls-Royce","Aerospace"],["BA.L","BAE Systems","Defense"],["EXPN.L","Experian","Information"],
  ["RELX.L","RELX","Information"],["INF.L","Informa","Information"],["WPP.L","WPP","Advertising"],
  ["CRH.L","CRH","Materials"],["SMDS.L","DS Smith","Packaging"],["BNZL.L","Bunzl","Distribution"],
  ["JD.L","JD Sports","Retail"],["BRBY.L","Burberry","Luxury"],["FLTR.L","Flutter","Gaming"],["ENT.L","Entain","Gaming"],
  ["LSEG.L","London Stock Exchange","Finance"],["ICP.L","Intermediate Capital","Asset Management"],
  ["3IN.L","3i Group","Investment"],["ADM.L","Admiral","Insurance"],["HL.L","Hargreaves Lansdown","Brokerage"],
  ["RTO.L","Rentokil","Services"],["SN.L","Smith & Nephew","Medical Devices"],["MRO.L","Melrose Industries","Industrial"],
  ["BDEV.L","Barratt Developments","Construction"],["BKG.L","Berkeley Group","Construction"],["TW.L","Taylor Wimpey","Construction"],
  ["PSN.L","Persimmon","Construction"],["LAND.L","Land Securities","REIT"],["BLND.L","British Land","REIT"],
  ["SGRO.L","Segro","REIT"],["AHT.L","Ashtead","Industrial"],["WEIR.L","Weir Group","Industrial"],
  ["SMIN.L","Smiths Group","Industrial"],["IHG.L","IHG Hotels","Hospitality"],["WTB.L","Whitbread","Hospitality"],
];

// =============== Japan (TSE) ===============
const JP: Mini[] = [
  ["7203.T","Toyota","Automotive"],["6758.T","Sony","Electronics"],["9984.T","SoftBank","Telecom"],
  ["6861.T","Keyence","Industrial"],["8306.T","Mitsubishi UFJ","Banking"],["6098.T","Recruit","HR"],
  ["9432.T","NTT","Telecom"],["9433.T","KDDI","Telecom"],["9434.T","SoftBank Corp","Telecom"],
  ["4063.T","Shin-Etsu Chemical","Chemicals"],["8035.T","Tokyo Electron","Semiconductors"],["6594.T","Nidec","Electronics"],
  ["6857.T","Advantest","Semiconductors"],["7974.T","Nintendo","Gaming"],["9983.T","Fast Retailing","Retail"],
  ["6501.T","Hitachi","Industrial"],["6503.T","Mitsubishi Electric","Industrial"],["6752.T","Panasonic","Electronics"],
  ["6701.T","NEC","Technology"],["6702.T","Fujitsu","Technology"],["8001.T","Itochu","Trading"],["8002.T","Marubeni","Trading"],
  ["8031.T","Mitsui","Trading"],["8053.T","Sumitomo Corp","Trading"],["8058.T","Mitsubishi Corp","Trading"],
  ["8316.T","Sumitomo Mitsui FG","Banking"],["8411.T","Mizuho","Banking"],["8604.T","Nomura","Brokerage"],
  ["8725.T","MS&AD","Insurance"],["8766.T","Tokio Marine","Insurance"],["8801.T","Mitsui Fudosan","REIT"],
  ["8802.T","Mitsubishi Estate","REIT"],["9020.T","JR East","Rail"],["9021.T","JR West","Rail"],
  ["9022.T","JR Central","Rail"],["7267.T","Honda","Automotive"],["7269.T","Suzuki","Automotive"],["7270.T","Subaru","Automotive"],
  ["7201.T","Nissan","Automotive"],["7211.T","Mitsubishi Motors","Automotive"],["6902.T","Denso","Auto Parts"],
  ["5108.T","Bridgestone","Tires"],["4502.T","Takeda Pharmaceutical","Pharma"],["4503.T","Astellas Pharma","Pharma"],
  ["4519.T","Chugai Pharma","Pharma"],["4901.T","Fujifilm","Imaging"],["4452.T","Kao","Consumer"],
  ["2914.T","Japan Tobacco","Tobacco"],["3382.T","Seven & i","Retail"],["8267.T","AEON","Retail"],
  ["3092.T","ZOZO","E-commerce"],["4324.T","Dentsu Group","Advertising"],["4543.T","Terumo","Medical Devices"],
  ["6981.T","Murata","Electronics"],["7733.T","Olympus","Medical Devices"],["6273.T","SMC","Industrial"],
  ["6367.T","Daikin","Industrial"],["6326.T","Kubota","Industrial"],["6954.T","FANUC","Industrial"],
];

// =============== China (HKEX + SSE + ADRs) ===============
const CN: Mini[] = [
  ["0700.HK","Tencent","Technology"],["9988.HK","Alibaba HK","E-commerce"],["3690.HK","Meituan","Food Delivery"],
  ["9618.HK","JD.com HK","E-commerce"],["1810.HK","Xiaomi","Electronics"],["2318.HK","Ping An","Insurance"],
  ["1299.HK","AIA","Insurance"],["0941.HK","China Mobile","Telecom"],["0939.HK","CCB","Banking"],
  ["1398.HK","ICBC","Banking"],["3988.HK","Bank of China","Banking"],["2628.HK","China Life","Insurance"],
  ["0883.HK","CNOOC","Energy"],["0857.HK","PetroChina","Energy"],["0386.HK","Sinopec","Energy"],
  ["1109.HK","CR Land","Real Estate"],["1113.HK","CK Asset","Real Estate"],["0016.HK","Sun Hung Kai","Real Estate"],
  ["0001.HK","CK Hutchison","Conglomerate"],["0011.HK","Hang Seng Bank","Banking"],["0005.HK","HSBC HK","Banking"],
  ["1928.HK","Sands China","Hospitality"],["0027.HK","Galaxy Entertainment","Hospitality"],
  ["2020.HK","ANTA Sports","Apparel"],["6862.HK","Haidilao","Restaurants"],["2331.HK","Li Ning","Apparel"],
  ["9999.HK","NetEase","Gaming"],["9888.HK","Baidu HK","Technology"],["9961.HK","Trip.com","Travel"],
  ["1024.HK","Kuaishou","Social Media"],["6618.HK","JD Health","Healthcare"],["2382.HK","Sunny Optical","Optics"],
  ["0992.HK","Lenovo","Technology"],["1211.HK","BYD","Automotive"],["0175.HK","Geely","Automotive"],
  ["2238.HK","GAC Group","Automotive"],["0728.HK","China Telecom","Telecom"],["0762.HK","China Unicom","Telecom"],
  ["600519.SS","Kweichow Moutai","Beverages"],["601318.SS","Ping An A","Insurance"],["600036.SS","CMB","Banking"],
  ["601398.SS","ICBC A","Banking"],["600276.SS","Hengrui Pharma","Pharma"],["600887.SS","Yili","Food"],
  ["601888.SS","China Tourism","Retail"],["600030.SS","CITIC Securities","Brokerage"],
  ["BABA","Alibaba ADR","E-commerce"],["JD","JD.com ADR","E-commerce"],["PDD","PDD Holdings","E-commerce"],
  ["BIDU","Baidu ADR","Technology"],["NIO","NIO","Automotive"],["XPEV","XPeng","Automotive"],["LI","Li Auto","Automotive"],
  ["BILI","Bilibili","Streaming"],["TME","Tencent Music","Streaming"],["IQ","iQIYI","Streaming"],
];

// =============== Saudi (Tadawul) ===============
const SA: Mini[] = [
  ["2222.SR","Saudi Aramco","Energy"],["1120.SR","Al Rajhi Bank","Banking"],["2010.SR","SABIC","Petrochemicals"],
  ["7010.SR","STC","Telecom"],["1180.SR","Saudi National Bank","Banking"],["2280.SR","Almarai","Food"],
  ["1211.SR","Maaden","Mining"],["1080.SR","Arab National Bank","Banking"],["1050.SR","Banque Saudi Fransi","Banking"],
  ["1060.SR","Saudi British Bank","Banking"],["1140.SR","Bank Albilad","Banking"],["1150.SR","Alinma Bank","Banking"],
  ["1010.SR","Riyad Bank","Banking"],["1020.SR","Bank Aljazira","Banking"],["1030.SR","SAIB","Banking"],
  ["2020.SR","SABIC Agri-Nutrients","Petrochemicals"],["2030.SR","SARCO","Industrial"],["2040.SR","Saudi Ceramics","Materials"],
  ["2050.SR","Savola Group","Food"],["2060.SR","Tasnee","Petrochemicals"],["2080.SR","Gasco","Energy"],
  ["2082.SR","ACWA Power","Utilities"],["2090.SR","Gulf Chemicals","Chemicals"],["2100.SR","Wafrah","Industrial"],
  ["2110.SR","Saudi Cable","Industrial"],["2120.SR","SAIC","Industrial"],["2130.SR","SIDC","Investment"],
  ["2140.SR","Al-Ahsa Dev.","Real Estate"],["2150.SR","Zoujaj","Industrial"],["2160.SR","Amiantit","Industrial"],
  ["2170.SR","Alujain","Industrial"],["2190.SR","SISCO","Logistics"],["2200.SR","Arabian Pipes","Industrial"],
  ["2210.SR","NAMA Chemicals","Chemicals"],["2220.SR","National Metal","Industrial"],["2230.SR","Saudi Chemical","Chemicals"],
  ["2240.SR","Zamil Industrial","Industrial"],["2250.SR","SIIG","Petrochemicals"],["2260.SR","SAFCO","Petrochemicals"],
  ["2270.SR","SADAFCO","Food"],["2290.SR","Yanbu National","Petrochemicals"],["2300.SR","SPM","Industrial"],
  ["2310.SR","Sipchem","Petrochemicals"],["2320.SR","Al Babtain","Industrial"],["2330.SR","Advanced","Petrochemicals"],
  ["2340.SR","Al-Abdullatif","Industrial"],["2350.SR","Saudi Kayan","Petrochemicals"],["2360.SR","SVCP","Industrial"],
  ["2370.SR","MESC","Industrial"],["2380.SR","Petrochem","Petrochemicals"],["2381.SR","Arabian Drilling","Energy"],
  ["3001.SR","Holy Makkah","Real Estate"],["3002.SR","NGC","Industrial"],["3003.SR","City Cement","Materials"],
  ["3004.SR","Northern Cement","Materials"],["3005.SR","Umm Al-Qura","Materials"],["3007.SR","Zahrat Al Waha","Industrial"],
  ["3008.SR","Alkathiri","Industrial"],["3010.SR","Arabian Cement","Materials"],["3020.SR","Yamamah Cement","Materials"],
  ["3030.SR","Saudi Cement","Materials"],["3040.SR","Qassim Cement","Materials"],["3050.SR","Southern Cement","Materials"],
  ["3060.SR","Yanbu Cement","Materials"],["3080.SR","Eastern Cement","Materials"],["3090.SR","Tabuk Cement","Materials"],
  ["4001.SR","A.Othaim Markets","Retail"],["4002.SR","Mouwasat","Healthcare"],["4003.SR","Extra","Retail"],
  ["4004.SR","Dallah Healthcare","Healthcare"],["4005.SR","Care","Healthcare"],["4006.SR","Farm Superstores","Retail"],
  ["4007.SR","Al Hammadi","Healthcare"],["4008.SR","SACO","Retail"],["4009.SR","Care Medical","Healthcare"],
  ["4011.SR","Lazurde","Retail"],["4013.SR","Sulaiman Al Habib","Healthcare"],["4030.SR","Bahri","Logistics"],
  ["4040.SR","Saudi Public Transport","Transport"],["4050.SR","SASCO","Transport"],["4070.SR","Tihama","Advertising"],
  ["4080.SR","Saudi Research","Media"],["4090.SR","Tihama Adv","Advertising"],["4100.SR","Al-Baha","Investment"],
  ["4110.SR","BATIC","Investment"],["4150.SR","Arriyadh Dev.","Real Estate"],["4160.SR","Thimar","Industrial"],
  ["4170.SR","Tecom","Hospitality"],["4180.SR","Fitaihi","Retail"],["4190.SR","Jarir","Retail"],
  ["4200.SR","Aldrees","Energy"],["4210.SR","Saudi Research","Media"],["4220.SR","Emaar EC","Real Estate"],
  ["4230.SR","Red Sea Housing","Construction"],["4240.SR","Al-Hokair","Hospitality"],["4250.SR","Jabal Omar","Real Estate"],
  ["4260.SR","Budget Saudi","Mobility"],["4270.SR","Saudi Printing","Industrial"],["4280.SR","Kingdom Holding","Investment"],
  ["4290.SR","Alkhaleej Training","Education"],["4300.SR","Dar Al Arkan","Real Estate"],["4310.SR","KEC","Construction"],
  ["4320.SR","Al Andalus Property","Real Estate"],["4330.SR","Riyad REIT","REIT"],["6001.SR","Halwani Bros","Food"],
  ["6002.SR","Herfy Food","Restaurants"],["6004.SR","Saudi Industrial Export","Industrial"],["6010.SR","NADEC","Food"],
  ["6012.SR","Almarai","Food"],["6013.SR","Dr. Sulaiman","Healthcare"],["6014.SR","Almunajem","Food"],
  ["6015.SR","Americana","Food"],["6020.SR","GACO","Industrial"],["6040.SR","Tabuk Agri","Food"],
  ["6050.SR","Saudi Fisheries","Food"],["6060.SR","Sharqiyah Dev.","Real Estate"],["6070.SR","Aljouf","Food"],
  ["6090.SR","Jazan Dev.","Industrial"],["7020.SR","Etihad Etisalat (Mobily)","Telecom"],["7030.SR","Zain KSA","Telecom"],
  ["7040.SR","Etihad Atheeb","Telecom"],["7200.SR","MIS","Technology"],["7201.SR","Arab Sea","Information"],
  ["7202.SR","Solutions","IT Services"],["8010.SR","Tawuniya","Insurance"],["8020.SR","Malath","Insurance"],
  ["8030.SR","MEDGULF","Insurance"],["8040.SR","Allianz SF","Insurance"],["8050.SR","Salama","Insurance"],
  ["8060.SR","Walaa","Insurance"],["8070.SR","Arabian Shield","Insurance"],["8080.SR","SAICO","Insurance"],
  ["8100.SR","SABB Takaful","Insurance"],["8120.SR","Gulf Union","Insurance"],["8150.SR","ACIG","Insurance"],
  ["8160.SR","AICC","Insurance"],["8170.SR","Alalamiya","Insurance"],["8180.SR","Al Sagr","Insurance"],
  ["8190.SR","UCA","Insurance"],["8200.SR","Saudi Re","Insurance"],["8210.SR","Bupa Arabia","Insurance"],
  ["8230.SR","Takaful Al-Rajhi","Insurance"],["8240.SR","Chubb Arabia","Insurance"],["8250.SR","AXA Cooperative","Insurance"],
  ["8260.SR","Gulf General","Insurance"],["8270.SR","Buruj","Insurance"],["8280.SR","Liva","Insurance"],
  ["8300.SR","Wataniya","Insurance"],["8310.SR","Amana","Insurance"],["8311.SR","Enaya","Insurance"],
  ["8313.SR","Rasan","Insurance"],
];

// =============== UAE (ADX + DFM) ===============
const UAE: Mini[] = [
  ["EMAAR.AE","Emaar Properties","Real Estate"],["EAND.AE","e&","Telecom"],["FAB.AE","First Abu Dhabi Bank","Banking"],
  ["DEWA.AE","DEWA","Utilities"],["ADNOCDIST.AE","ADNOC Distribution","Energy"],["ALDAR.AE","Aldar Properties","Real Estate"],
  ["ADCB.AE","Abu Dhabi Commercial Bank","Banking"],["DIB.AE","Dubai Islamic Bank","Banking"],["EMIRATESNBD.AE","Emirates NBD","Banking"],
  ["MASQ.AE","Mashreq","Banking"],["CBD.AE","CBD","Banking"],["RAKBANK.AE","RAKBANK","Banking"],
  ["TAQA.AE","TAQA","Utilities"],["ADPORTS.AE","AD Ports","Logistics"],["BOROUGE.AE","Borouge","Petrochemicals"],
  ["ADNH.AE","ADNH","Hospitality"],["MULTIPLY.AE","Multiply Group","Investment"],["ALPHADHABI.AE","Alpha Dhabi","Investment"],
  ["IHC.AE","IHC","Investment"],["AGTHIA.AE","Agthia","Food"],["EMIRATESDRIV.AE","Emirates Driving","Services"],
  ["PURE.AE","Pure Health","Healthcare"],["ADNOCGAS.AE","ADNOC Gas","Energy"],["ADNOCDRILL.AE","ADNOC Drilling","Energy"],
  ["ADNOCLS.AE","ADNOC Logistics","Logistics"],["FERTIGLOBE.AE","Fertiglobe","Petrochemicals"],
  ["AMR.AE","Americana Restaurants","Restaurants"],["PRESIGHT.AE","Presight AI","Technology"],
  ["EMAARDEV.AE","Emaar Development","Real Estate"],["DAMAC.AE","Damac","Real Estate"],["UNION.AE","Union Properties","Real Estate"],
  ["DEYAAR.AE","Deyaar","Real Estate"],["TECOM.AE","TECOM Group","Real Estate"],["EMPOWER.AE","Empower","Utilities"],
  ["SALIK.AE","Salik","Services"],["TAALEEM.AE","Taaleem","Education"],["GFH.AE","GFH","Finance"],
  ["ARMX.AE","Aramex","Logistics"],["DXBE.AE","DXB Entertainments","Entertainment"],["DUBHLDG.AE","Dubai Holding","Investment"],
];

// =============== Qatar (QSE) ===============
const QA: Mini[] = [
  ["QNBK.QA","Qatar National Bank","Banking"],["QIBK.QA","Qatar Islamic Bank","Banking"],["CBQK.QA","Commercial Bank","Banking"],
  ["MARK.QA","Masraf Al Rayan","Banking"],["DHBK.QA","Doha Bank","Banking"],["QIIK.QA","Qatar International Islamic","Banking"],
  ["IQCD.QA","Industries Qatar","Industrial"],["QGTS.QA","Qatar Gas Transport","Energy"],["QEWS.QA","Qatar Electricity & Water","Utilities"],
  ["MPHC.QA","Mesaieed Petrochemical","Petrochemicals"],["ORDS.QA","Ooredoo","Telecom"],["VFQS.QA","Vodafone Qatar","Telecom"],
  ["MERS.QA","Al Meera","Retail"],["BLDN.QA","Baladna","Food"],["QFLS.QA","Qatar Fuel","Energy"],
  ["GISS.QA","Gulf International Services","Energy"],["QGRI.QA","Qatar General Insurance","Insurance"],
  ["QATI.QA","Qatar Insurance","Insurance"],["BRES.QA","Barwa Real Estate","Real Estate"],["UDCD.QA","UDC","Real Estate"],
  ["ERES.QA","Ezdan Holding","Real Estate"],["MCGS.QA","Medicare Group","Healthcare"],["QAMC.QA","Qatar Aluminum","Industrial"],
  ["AHCS.QA","Aamal Company","Conglomerate"],["MCCS.QA","Mannai Corp","Conglomerate"],
];

export const STOCKS_UNIVERSE: Record<StockRegion, CompanyDef[]> = {
  us: expand(US, "USD", 150),
  eu: expand(EU, "EUR", 90),
  uk: expand(UK, "GBp", 1500),
  japan: expand(JP, "JPY", 4500),
  china: expand(CN, "HKD", 80),
  saudi: expand(SA, "SAR", 45),
  uae: expand(UAE, "AED", 8),
  qatar: expand(QA, "QAR", 15),
};

export const UNIVERSE_COUNT = Object.values(STOCKS_UNIVERSE).reduce((s, a) => s + a.length, 0);
