import { createFileRoute } from "@tanstack/react-router";

const MARKETS = [
  {
    region: "saudi",
    nameAr: "السوق السعودي",
    nameEn: "Saudi Exchange (Tadawul)",
    suffix: ".SR",
    examples: ["2222.SR", "1120.SR", "7010.SR"],
    assetClass: "saudi_stock",
    providers: ["sahmk", "fmp", "twelvedata", "alphavantage"],
    status: "enabled",
  },
  {
    region: "gcc",
    nameAr: "أسواق الخليج",
    nameEn: "GCC Markets",
    suffix: ".QA, .DU, .AD, .KW, .BH, .OM",
    examples: ["QNBK.QA", "FAB.AD", "NBK.KW"],
    assetClass: "gcc_stock",
    providers: ["fmp", "twelvedata", "alphavantage"],
    status: "partial",
  },
  {
    region: "us",
    nameAr: "السوق الأمريكي",
    nameEn: "US Markets (NYSE/NASDAQ)",
    suffix: "none",
    examples: ["AAPL", "MSFT", "NVDA", "TSLA", "SPY", "QQQ"],
    assetClass: "us_stock",
    providers: ["fmp", "twelvedata", "alphavantage", "finnhub"],
    status: "enabled",
  },
  {
    region: "uk",
    nameAr: "السوق البريطاني",
    nameEn: "London Stock Exchange",
    suffix: ".L",
    examples: ["HSBA.L", "BP.L", "SHEL.L", "VOD.L"],
    assetClass: "uk_stock",
    providers: ["fmp", "twelvedata", "alphavantage"],
    status: "enabled",
  },
  {
    region: "europe",
    nameAr: "الأسواق الأوروبية",
    nameEn: "European Markets",
    suffix: ".DE, .PA, .MI, .MC, .AS, .SW",
    examples: ["SAP.DE", "BMW.DE", "MC.PA", "AIR.PA", "SIE.DE"],
    assetClass: "european_stock",
    providers: ["fmp", "twelvedata", "alphavantage"],
    status: "enabled",
  },
  {
    region: "china",
    nameAr: "الأسواق الصينية",
    nameEn: "China Markets (Shanghai/Shenzhen)",
    suffix: ".SS, .SZ",
    examples: ["600519.SS", "000001.SZ"],
    assetClass: "china_stock",
    providers: ["fmp", "twelvedata", "alphavantage"],
    status: "enabled",
  },
  {
    region: "hongkong",
    nameAr: "سوق هونغ كونغ",
    nameEn: "Hong Kong Exchange",
    suffix: ".HK",
    examples: ["0700.HK", "9988.HK"],
    assetClass: "hongkong_stock",
    providers: ["fmp", "twelvedata", "alphavantage"],
    status: "enabled",
  },
  {
    region: "crypto",
    nameAr: "العملات الرقمية",
    nameEn: "Crypto",
    suffix: "USDT, /USD",
    examples: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
    assetClass: "crypto",
    providers: ["binance", "coingecko", "twelvedata"],
    status: "enabled",
  },
  {
    region: "forex",
    nameAr: "سوق العملات",
    nameEn: "Forex",
    suffix: "pair",
    examples: ["EURUSD", "GBPUSD", "USDJPY", "USD/SAR"],
    assetClass: "forex",
    providers: ["twelvedata", "fmp", "alphavantage"],
    status: "enabled",
  },
  {
    region: "metals",
    nameAr: "المعادن الثمينة",
    nameEn: "Precious Metals",
    suffix: "USD",
    examples: ["XAUUSD", "XAGUSD", "GOLD", "SILVER"],
    assetClass: "metal",
    providers: ["twelvedata", "commodityprice", "fmp"],
    status: "enabled",
  },
  {
    region: "commodities",
    nameAr: "السلع",
    nameEn: "Commodities",
    suffix: "",
    examples: ["WTI", "BRENT", "NATGAS"],
    assetClass: "commodity",
    providers: ["commodityprice", "fmp", "twelvedata"],
    status: "enabled",
  },
];

export const Route = createFileRoute("/api/public/supported-markets")({
  server: {
    handlers: {
      GET: async () => {
        return new Response(JSON.stringify(MARKETS, null, 2), {
          headers: { "Content-Type": "application/json", "Cache-Control": "public, max-age=300" },
        });
      },
    },
  },
});
