import type { KnowledgeChunk, KnowledgeDocument, KnowledgeReference, KnowledgeTopic } from "@/lib/ai/knowledge/schema";

const createdAt = "2026-05-24T00:00:00.000Z";

export const knowledge_documents: KnowledgeDocument[] = [
  {
    id: "graham-margin-safety",
    title: "Margin of Safety",
    author: "Benjamin Graham",
    sourceType: "book_reference",
    category: "value investing",
    topic: "valuation discipline",
    summaryAr: "مبدأ هامش الأمان يطلب شراء الأصل بسعر أقل من قيمته المقدرة لتقليل أثر الخطأ وعدم اليقين.",
    summaryEn: "Margin of safety means buying below estimated intrinsic value to reduce error and uncertainty.",
    tags: ["valuation", "safety", "value investing"],
    confidence: 92,
    reference: "Short concept summary inspired by Benjamin Graham's value investing framework.",
    createdAt,
  },
  {
    id: "buffett-quality-moat",
    title: "Quality and Economic Moats",
    author: "Warren Buffett",
    sourceType: "investor_principle",
    category: "fundamental analysis",
    topic: "business quality",
    summaryAr: "الأعمال ذات الخندق الاقتصادي والقدرة على توليد نقد مستدام تستحق وزناً أعلى عند تقييم الأسهم.",
    summaryEn: "Businesses with durable moats and persistent cash generation deserve higher-quality consideration.",
    tags: ["moat", "quality", "cash flow"],
    confidence: 90,
    reference: "Short concept summary of Buffett-style business quality thinking.",
    createdAt,
  },
  {
    id: "munger-inversion",
    title: "Inversion and Mental Models",
    author: "Charlie Munger",
    sourceType: "investor_principle",
    category: "behavioral finance",
    topic: "decision quality",
    summaryAr: "التفكير بالعكس يساعد على كشف الأخطاء: اسأل ما الذي قد يجعل القرار فاشلاً قبل البحث عما يجعله ناجحاً.",
    summaryEn: "Inversion improves decision quality by asking what could make a decision fail before seeking upside.",
    tags: ["inversion", "bias", "mental models"],
    confidence: 88,
    reference: "Short concept summary of Munger's inversion principle.",
    createdAt,
  },
  {
    id: "soros-reflexivity",
    title: "Reflexivity",
    author: "George Soros",
    sourceType: "market_framework",
    category: "reflexivity",
    topic: "feedback loops",
    summaryAr: "الأسعار والتوقعات يؤثر كل منهما في الآخر؛ ارتفاع السعر قد يعزز القصة مؤقتاً حتى تنقلب الحلقة.",
    summaryEn: "Prices and expectations can reinforce each other, creating feedback loops that may later reverse.",
    tags: ["reflexivity", "feedback", "cycles"],
    confidence: 84,
    reference: "Short concept summary of reflexivity in markets.",
    createdAt,
  },
  {
    id: "dalio-cycle-liquidity",
    title: "Debt Cycles and Liquidity",
    author: "Ray Dalio",
    sourceType: "market_framework",
    category: "liquidity",
    topic: "macro cycles",
    summaryAr: "السيولة ودورات الائتمان تؤثر في أسعار الأصول؛ التوسع يدعم المخاطرة والانكماش يرفع الحاجة للدفاع.",
    summaryEn: "Liquidity and credit cycles influence asset prices; expansion supports risk assets while contraction favors defense.",
    tags: ["liquidity", "credit", "macro"],
    confidence: 86,
    reference: "Short concept summary of debt/liquidity cycle thinking.",
    createdAt,
  },
  {
    id: "mpt-diversification",
    title: "Diversification and Correlation",
    author: "Modern Portfolio Theory",
    sourceType: "academic_framework",
    category: "portfolio theory",
    topic: "diversification",
    summaryAr: "تقليل الارتباط بين الأصول قد يخفض تذبذب المحفظة دون التخلي الكامل عن العائد المتوقع.",
    summaryEn: "Lower correlation among holdings can reduce portfolio volatility without fully sacrificing expected return.",
    tags: ["diversification", "correlation", "portfolio"],
    confidence: 89,
    reference: "Short educational summary of diversification concepts.",
    createdAt,
  },
  {
    id: "risk-management-sizing",
    title: "Position Sizing and Drawdown Control",
    author: "Risk Management",
    sourceType: "risk_framework",
    category: "risk management",
    topic: "capital preservation",
    summaryAr: "حجم المركز يجب أن يتناسب مع جودة القرار واحتمال الخسارة؛ حماية رأس المال تسبق تعظيم الربح.",
    summaryEn: "Position size should scale with decision quality and downside risk; capital preservation comes first.",
    tags: ["risk", "position sizing", "drawdown"],
    confidence: 94,
    reference: "Internal risk management concept summary.",
    createdAt,
  },
  {
    id: "market-cycles-crisis",
    title: "Market Cycles and Crisis Memory",
    author: "Market Cycles",
    sourceType: "market_framework",
    category: "crisis history",
    topic: "cycle awareness",
    summaryAr: "الأزمات غالباً تبدأ من رافعة مالية زائدة أو سيولة ضعيفة أو ثقة مفرطة؛ مؤشرات الضغط تستحق تخفيض المخاطر.",
    summaryEn: "Crises often emerge from excess leverage, weak liquidity, or overconfidence; stress indicators justify risk reduction.",
    tags: ["crisis", "cycles", "leverage"],
    confidence: 85,
    reference: "Short concept summary from market cycle history.",
    createdAt,
  },
  {
    id: "technical-trend-structure",
    title: "Trend Structure",
    author: "Technical Analysis",
    sourceType: "market_framework",
    category: "technical analysis",
    topic: "trend and timing",
    summaryAr: "اتجاه السعر والزخم يساعدان في توقيت الدخول والخروج، لكنهما لا يكفيان دون إدارة مخاطر.",
    summaryEn: "Trend and momentum help timing, but they are incomplete without risk management.",
    tags: ["trend", "momentum", "timing"],
    confidence: 78,
    reference: "Short technical analysis principle summary.",
    createdAt,
  },
  {
    id: "inflation-commodities",
    title: "Inflation and Real Assets",
    author: "Macro Investing",
    sourceType: "market_framework",
    category: "inflation",
    topic: "commodities",
    summaryAr: "في بيئات التضخم قد تستفيد السلع والأصول الحقيقية، لكن ارتفاع الفائدة قد يضغط التقييمات.",
    summaryEn: "Inflation can support commodities and real assets, while higher rates may pressure valuations.",
    tags: ["inflation", "commodities", "rates"],
    confidence: 82,
    reference: "Short macro investing concept summary.",
    createdAt,
  },
];

export const knowledge_chunks: KnowledgeChunk[] = knowledge_documents.map((doc) => ({
  ...doc,
  id: `${doc.id}-chunk-1`,
  documentId: doc.id,
  chunkTextAr: doc.summaryAr,
  chunkTextEn: doc.summaryEn,
}));

export const knowledge_topics: KnowledgeTopic[] = Array.from(new Set(knowledge_documents.map((doc) => doc.category))).map((category) => {
  const doc = knowledge_documents.find((item) => item.category === category)!;
  return {
    ...doc,
    id: `topic-${category.replace(/\s+/g, "-")}`,
    title: category,
    topic: category,
    documentCount: knowledge_documents.filter((item) => item.category === category).length,
  };
});

export const knowledge_references: KnowledgeReference[] = knowledge_documents.map((doc) => ({
  ...doc,
  id: `ref-${doc.id}`,
  referenceType: doc.sourceType === "investor_principle" ? "person" : "concept",
}));
