/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchlistRouteImport } from './routes/_app/watchlist'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppSystemHealthRouteImport } from './routes/_app/system-health'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppSignalsRouteImport } from './routes/_app/signals'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScannerRouteImport } from './routes/_app/scanner'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPortfoliosRouteImport } from './routes/_app/portfolios'
import { Route as AppPaperTradingRouteImport } from './routes/_app/paper-trading'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppMarketsRouteImport } from './routes/_app/markets'
import { Route as AppHeatmapRouteImport } from './routes/_app/heatmap'
import { Route as AppGrowthPlanRouteImport } from './routes/_app/growth-plan'
import { Route as AppExternalAccountsRouteImport } from './routes/_app/external-accounts'
import { Route as AppErrorLogsRouteImport } from './routes/_app/error-logs'
import { Route as AppEmailDiagnosticsRouteImport } from './routes/_app/email-diagnostics'
import { Route as AppDomainRouteImport } from './routes/_app/domain'
import { Route as AppDepositRouteImport } from './routes/_app/deposit'
import { Route as AppDbDiagnosticsRouteImport } from './routes/_app/db-diagnostics'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppBankAccountsRouteImport } from './routes/_app/bank-accounts'
import { Route as AppArchiveRouteImport } from './routes/_app/archive'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAiDashboardRouteImport } from './routes/_app/ai-dashboard'
import { Route as AppAdvisorRouteImport } from './routes/_app/advisor'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api/webhooks/paddle'
import { Route as ApiWebhooksLemonsqueezyRouteImport } from './routes/api/webhooks/lemonsqueezy'
import { Route as ApiPublicMoyasarWebhookRouteImport } from './routes/api/public/moyasar-webhook'
import { Route as ApiPublicEmailConfigCheckRouteImport } from './routes/api/public/email-config-check'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicAlertsEvaluateRouteImport } from './routes/api/public/alerts/evaluate'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemHealthRoute = AppSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfoliosRoute = AppPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AppRoute,
} as any)
const AppPaperTradingRoute = AppPaperTradingRouteImport.update({
  id: '/paper-trading',
  path: '/paper-trading',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthPlanRoute = AppGrowthPlanRouteImport.update({
  id: '/growth-plan',
  path: '/growth-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppExternalAccountsRoute = AppExternalAccountsRouteImport.update({
  id: '/external-accounts',
  path: '/external-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppErrorLogsRoute = AppErrorLogsRouteImport.update({
  id: '/error-logs',
  path: '/error-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailDiagnosticsRoute = AppEmailDiagnosticsRouteImport.update({
  id: '/email-diagnostics',
  path: '/email-diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainRoute = AppDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDiagnosticsRoute = AppDbDiagnosticsRouteImport.update({
  id: '/db-diagnostics',
  path: '/db-diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBankAccountsRoute = AppBankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiDashboardRoute = AppAiDashboardRouteImport.update({
  id: '/ai-dashboard',
  path: '/ai-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLemonsqueezyRoute = ApiWebhooksLemonsqueezyRouteImport.update({
  id: '/api/webhooks/lemonsqueezy',
  path: '/api/webhooks/lemonsqueezy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMoyasarWebhookRoute = ApiPublicMoyasarWebhookRouteImport.update({
  id: '/api/public/moyasar-webhook',
  path: '/api/public/moyasar-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailConfigCheckRoute =
  ApiPublicEmailConfigCheckRouteImport.update({
    id: '/api/public/email-config-check',
    path: '/api/public/email-config-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAlertsEvaluateRoute = ApiPublicAlertsEvaluateRouteImport.update({
  id: '/api/public/alerts/evaluate',
  path: '/api/public/alerts/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/advisor': typeof AppAdvisorRoute
  '/ai-dashboard': typeof AppAiDashboardRoute
  '/alerts': typeof AppAlertsRoute
  '/archive': typeof AppArchiveRoute
  '/bank-accounts': typeof AppBankAccountsRoute
  '/billing': typeof AppBillingRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/db-diagnostics': typeof AppDbDiagnosticsRoute
  '/deposit': typeof AppDepositRoute
  '/domain': typeof AppDomainRoute
  '/email-diagnostics': typeof AppEmailDiagnosticsRoute
  '/error-logs': typeof AppErrorLogsRoute
  '/external-accounts': typeof AppExternalAccountsRoute
  '/growth-plan': typeof AppGrowthPlanRoute
  '/heatmap': typeof AppHeatmapRoute
  '/markets': typeof AppMarketsRoute
  '/members': typeof AppMembersRoute
  '/paper-trading': typeof AppPaperTradingRoute
  '/portfolios': typeof AppPortfoliosRoute
  '/profile': typeof AppProfileRoute
  '/scanner': typeof AppScannerRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/system-health': typeof AppSystemHealthRoute
  '/wallet': typeof AppWalletRoute
  '/watchlist': typeof AppWatchlistRoute
  '/api/public/email-config-check': typeof ApiPublicEmailConfigCheckRoute
  '/api/public/moyasar-webhook': typeof ApiPublicMoyasarWebhookRoute
  '/api/webhooks/lemonsqueezy': typeof ApiWebhooksLemonsqueezyRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/public/alerts/evaluate': typeof ApiPublicAlertsEvaluateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/advisor': typeof AppAdvisorRoute
  '/ai-dashboard': typeof AppAiDashboardRoute
  '/alerts': typeof AppAlertsRoute
  '/archive': typeof AppArchiveRoute
  '/bank-accounts': typeof AppBankAccountsRoute
  '/billing': typeof AppBillingRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/db-diagnostics': typeof AppDbDiagnosticsRoute
  '/deposit': typeof AppDepositRoute
  '/domain': typeof AppDomainRoute
  '/email-diagnostics': typeof AppEmailDiagnosticsRoute
  '/error-logs': typeof AppErrorLogsRoute
  '/external-accounts': typeof AppExternalAccountsRoute
  '/growth-plan': typeof AppGrowthPlanRoute
  '/heatmap': typeof AppHeatmapRoute
  '/markets': typeof AppMarketsRoute
  '/members': typeof AppMembersRoute
  '/paper-trading': typeof AppPaperTradingRoute
  '/portfolios': typeof AppPortfoliosRoute
  '/profile': typeof AppProfileRoute
  '/scanner': typeof AppScannerRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/system-health': typeof AppSystemHealthRoute
  '/wallet': typeof AppWalletRoute
  '/watchlist': typeof AppWatchlistRoute
  '/api/public/email-config-check': typeof ApiPublicEmailConfigCheckRoute
  '/api/public/moyasar-webhook': typeof ApiPublicMoyasarWebhookRoute
  '/api/webhooks/lemonsqueezy': typeof ApiWebhooksLemonsqueezyRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/public/alerts/evaluate': typeof ApiPublicAlertsEvaluateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_app/advisor': typeof AppAdvisorRoute
  '/_app/ai-dashboard': typeof AppAiDashboardRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/bank-accounts': typeof AppBankAccountsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/db-diagnostics': typeof AppDbDiagnosticsRoute
  '/_app/deposit': typeof AppDepositRoute
  '/_app/domain': typeof AppDomainRoute
  '/_app/email-diagnostics': typeof AppEmailDiagnosticsRoute
  '/_app/error-logs': typeof AppErrorLogsRoute
  '/_app/external-accounts': typeof AppExternalAccountsRoute
  '/_app/growth-plan': typeof AppGrowthPlanRoute
  '/_app/heatmap': typeof AppHeatmapRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/paper-trading': typeof AppPaperTradingRoute
  '/_app/portfolios': typeof AppPortfoliosRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/system-health': typeof AppSystemHealthRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/api/public/email-config-check': typeof ApiPublicEmailConfigCheckRoute
  '/api/public/moyasar-webhook': typeof ApiPublicMoyasarWebhookRoute
  '/api/webhooks/lemonsqueezy': typeof ApiWebhooksLemonsqueezyRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/public/alerts/evaluate': typeof ApiPublicAlertsEvaluateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/advisor'
    | '/ai-dashboard'
    | '/alerts'
    | '/archive'
    | '/bank-accounts'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/db-diagnostics'
    | '/deposit'
    | '/domain'
    | '/email-diagnostics'
    | '/error-logs'
    | '/external-accounts'
    | '/growth-plan'
    | '/heatmap'
    | '/markets'
    | '/members'
    | '/paper-trading'
    | '/portfolios'
    | '/profile'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/system-health'
    | '/wallet'
    | '/watchlist'
    | '/api/public/email-config-check'
    | '/api/public/moyasar-webhook'
    | '/api/webhooks/lemonsqueezy'
    | '/api/webhooks/paddle'
    | '/api/webhooks/stripe'
    | '/api/public/alerts/evaluate'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/advisor'
    | '/ai-dashboard'
    | '/alerts'
    | '/archive'
    | '/bank-accounts'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/db-diagnostics'
    | '/deposit'
    | '/domain'
    | '/email-diagnostics'
    | '/error-logs'
    | '/external-accounts'
    | '/growth-plan'
    | '/heatmap'
    | '/markets'
    | '/members'
    | '/paper-trading'
    | '/portfolios'
    | '/profile'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/system-health'
    | '/wallet'
    | '/watchlist'
    | '/api/public/email-config-check'
    | '/api/public/moyasar-webhook'
    | '/api/webhooks/lemonsqueezy'
    | '/api/webhooks/paddle'
    | '/api/webhooks/stripe'
    | '/api/public/alerts/evaluate'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/_app/advisor'
    | '/_app/ai-dashboard'
    | '/_app/alerts'
    | '/_app/archive'
    | '/_app/bank-accounts'
    | '/_app/billing'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/db-diagnostics'
    | '/_app/deposit'
    | '/_app/domain'
    | '/_app/email-diagnostics'
    | '/_app/error-logs'
    | '/_app/external-accounts'
    | '/_app/growth-plan'
    | '/_app/heatmap'
    | '/_app/markets'
    | '/_app/members'
    | '/_app/paper-trading'
    | '/_app/portfolios'
    | '/_app/profile'
    | '/_app/scanner'
    | '/_app/settings'
    | '/_app/signals'
    | '/_app/subscription'
    | '/_app/system-health'
    | '/_app/wallet'
    | '/_app/watchlist'
    | '/api/public/email-config-check'
    | '/api/public/moyasar-webhook'
    | '/api/webhooks/lemonsqueezy'
    | '/api/webhooks/paddle'
    | '/api/webhooks/stripe'
    | '/api/public/alerts/evaluate'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicEmailConfigCheckRoute: typeof ApiPublicEmailConfigCheckRoute
  ApiPublicMoyasarWebhookRoute: typeof ApiPublicMoyasarWebhookRoute
  ApiWebhooksLemonsqueezyRoute: typeof ApiWebhooksLemonsqueezyRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiPublicAlertsEvaluateRoute: typeof ApiPublicAlertsEvaluateRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-health': {
      id: '/_app/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AppSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolios': {
      id: '/_app/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof AppPortfoliosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paper-trading': {
      id: '/_app/paper-trading'
      path: '/paper-trading'
      fullPath: '/paper-trading'
      preLoaderRoute: typeof AppPaperTradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heatmap': {
      id: '/_app/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth-plan': {
      id: '/_app/growth-plan'
      path: '/growth-plan'
      fullPath: '/growth-plan'
      preLoaderRoute: typeof AppGrowthPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/external-accounts': {
      id: '/_app/external-accounts'
      path: '/external-accounts'
      fullPath: '/external-accounts'
      preLoaderRoute: typeof AppExternalAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/error-logs': {
      id: '/_app/error-logs'
      path: '/error-logs'
      fullPath: '/error-logs'
      preLoaderRoute: typeof AppErrorLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-diagnostics': {
      id: '/_app/email-diagnostics'
      path: '/email-diagnostics'
      fullPath: '/email-diagnostics'
      preLoaderRoute: typeof AppEmailDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domain': {
      id: '/_app/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof AppDomainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit': {
      id: '/_app/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db-diagnostics': {
      id: '/_app/db-diagnostics'
      path: '/db-diagnostics'
      fullPath: '/db-diagnostics'
      preLoaderRoute: typeof AppDbDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-accounts': {
      id: '/_app/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof AppBankAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-dashboard': {
      id: '/_app/ai-dashboard'
      path: '/ai-dashboard'
      fullPath: '/ai-dashboard'
      preLoaderRoute: typeof AppAiDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisor': {
      id: '/_app/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/lemonsqueezy': {
      id: '/api/webhooks/lemonsqueezy'
      path: '/api/webhooks/lemonsqueezy'
      fullPath: '/api/webhooks/lemonsqueezy'
      preLoaderRoute: typeof ApiWebhooksLemonsqueezyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moyasar-webhook': {
      id: '/api/public/moyasar-webhook'
      path: '/api/public/moyasar-webhook'
      fullPath: '/api/public/moyasar-webhook'
      preLoaderRoute: typeof ApiPublicMoyasarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-config-check': {
      id: '/api/public/email-config-check'
      path: '/api/public/email-config-check'
      fullPath: '/api/public/email-config-check'
      preLoaderRoute: typeof ApiPublicEmailConfigCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts/evaluate': {
      id: '/api/public/alerts/evaluate'
      path: '/api/public/alerts/evaluate'
      fullPath: '/api/public/alerts/evaluate'
      preLoaderRoute: typeof ApiPublicAlertsEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppAiDashboardRoute: typeof AppAiDashboardRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppArchiveRoute: typeof AppArchiveRoute
  AppBankAccountsRoute: typeof AppBankAccountsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDbDiagnosticsRoute: typeof AppDbDiagnosticsRoute
  AppDepositRoute: typeof AppDepositRoute
  AppDomainRoute: typeof AppDomainRoute
  AppEmailDiagnosticsRoute: typeof AppEmailDiagnosticsRoute
  AppErrorLogsRoute: typeof AppErrorLogsRoute
  AppExternalAccountsRoute: typeof AppExternalAccountsRoute
  AppGrowthPlanRoute: typeof AppGrowthPlanRoute
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppPaperTradingRoute: typeof AppPaperTradingRoute
  AppPortfoliosRoute: typeof AppPortfoliosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSystemHealthRoute: typeof AppSystemHealthRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppAiDashboardRoute: AppAiDashboardRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppArchiveRoute: AppArchiveRoute,
  AppBankAccountsRoute: AppBankAccountsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDbDiagnosticsRoute: AppDbDiagnosticsRoute,
  AppDepositRoute: AppDepositRoute,
  AppDomainRoute: AppDomainRoute,
  AppEmailDiagnosticsRoute: AppEmailDiagnosticsRoute,
  AppErrorLogsRoute: AppErrorLogsRoute,
  AppExternalAccountsRoute: AppExternalAccountsRoute,
  AppGrowthPlanRoute: AppGrowthPlanRoute,
  AppHeatmapRoute: AppHeatmapRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppMembersRoute: AppMembersRoute,
  AppPaperTradingRoute: AppPaperTradingRoute,
  AppPortfoliosRoute: AppPortfoliosRoute,
  AppProfileRoute: AppProfileRoute,
  AppScannerRoute: AppScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSystemHealthRoute: AppSystemHealthRoute,
  AppWalletRoute: AppWalletRoute,
  AppWatchlistRoute: AppWatchlistRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicEmailConfigCheckRoute: ApiPublicEmailConfigCheckRoute,
  ApiPublicMoyasarWebhookRoute: ApiPublicMoyasarWebhookRoute,
  ApiWebhooksLemonsqueezyRoute: ApiWebhooksLemonsqueezyRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiPublicAlertsEvaluateRoute: ApiPublicAlertsEvaluateRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
