/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppStocksRouteImport } from './routes/_app/stocks'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppMarketsRouteImport } from './routes/_app/markets'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBankAccountsRouteImport } from './routes/_app/bank-accounts'
import { Route as AppArchiveRouteImport } from './routes/_app/archive'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAdvisorRouteImport } from './routes/_app/advisor'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksRoute = AppStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBankAccountsRoute = AppBankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AppAdvisorRoute
  '/alerts': typeof AppAlertsRoute
  '/archive': typeof AppArchiveRoute
  '/bank-accounts': typeof AppBankAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/markets': typeof AppMarketsRoute
  '/members': typeof AppMembersRoute
  '/profile': typeof AppProfileRoute
  '/stocks': typeof AppStocksRoute
  '/wallet': typeof AppWalletRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AppAdvisorRoute
  '/alerts': typeof AppAlertsRoute
  '/archive': typeof AppArchiveRoute
  '/bank-accounts': typeof AppBankAccountsRoute
  '/dashboard': typeof AppDashboardRoute
  '/markets': typeof AppMarketsRoute
  '/members': typeof AppMembersRoute
  '/profile': typeof AppProfileRoute
  '/stocks': typeof AppStocksRoute
  '/wallet': typeof AppWalletRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/advisor': typeof AppAdvisorRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/bank-accounts': typeof AppBankAccountsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/stocks': typeof AppStocksRoute
  '/_app/wallet': typeof AppWalletRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/advisor'
    | '/alerts'
    | '/archive'
    | '/bank-accounts'
    | '/dashboard'
    | '/markets'
    | '/members'
    | '/profile'
    | '/stocks'
    | '/wallet'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/advisor'
    | '/alerts'
    | '/archive'
    | '/bank-accounts'
    | '/dashboard'
    | '/markets'
    | '/members'
    | '/profile'
    | '/stocks'
    | '/wallet'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/advisor'
    | '/_app/alerts'
    | '/_app/archive'
    | '/_app/bank-accounts'
    | '/_app/dashboard'
    | '/_app/markets'
    | '/_app/members'
    | '/_app/profile'
    | '/_app/stocks'
    | '/_app/wallet'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks': {
      id: '/_app/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AppStocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-accounts': {
      id: '/_app/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof AppBankAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisor': {
      id: '/_app/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppArchiveRoute: typeof AppArchiveRoute
  AppBankAccountsRoute: typeof AppBankAccountsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStocksRoute: typeof AppStocksRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppArchiveRoute: AppArchiveRoute,
  AppBankAccountsRoute: AppBankAccountsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppMembersRoute: AppMembersRoute,
  AppProfileRoute: AppProfileRoute,
  AppStocksRoute: AppStocksRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
