// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing variable(s): ${missing.join(', ')} — running in offline mode (auth disabled).`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    db: { schema: 'public' },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Minimal no-op stub used when Supabase env vars are absent (preview / CI).
// Returns empty resolved promises so auth hooks settle cleanly with null user.
function makeOfflineStub(): ReturnType<Exclude<ReturnType<typeof createSupabaseClient>, null>> {
  const noop = () => Promise.resolve({ data: {}, error: null });
  const auth = {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    signInWithPassword: noop,
    signUp: noop,
    signOut: () => Promise.resolve({ error: null }),
    resetPasswordForEmail: noop,
    updateUser: noop,
  };
  return { auth, from: () => ({ select: noop, insert: noop, update: noop, delete: noop, eq: () => ({ select: noop }) }), rpc: noop } as never;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as Exclude<ReturnType<typeof createSupabaseClient>, null>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    const client = _supabase ?? makeOfflineStub();
    return Reflect.get(client as object, prop, receiver);
  },
});

